import type { Therapist } from './types';

/**
 * SERVICE TEMPLATES FOR DATABASE SETUP
 * Copy paste these as new documents in Supabase
 */

export const SAMPLE_SERVICES = [
  {
    name: 'Massage Truyền Thống',
    nameEn: 'Traditional Massage',
    description: 'Massage toàn thân theo phương pháp truyền thống Việt Nam, giúp thư giãn cơ bắp',
    descriptionEn: 'Full body traditional Vietnamese massage for muscle relaxation',
    category: 'massage',
    icon: '💆',
    basePrice: 300000,
    duration: 60,
    image: 'https://via.placeholder.com/300x200?text=Massage',
    rating: 4.8,
    reviewCount: 245,
    isActive: true,
  },
  {
    name: 'Massage Chân',
    nameEn: 'Foot Massage',
    description: 'Massage chân và xoa bóp huyệt đạo giúp cải thiện tuần hoàn máu',
    descriptionEn: 'Foot massage to improve blood circulation',
    category: 'massage',
    icon: '🦶',
    basePrice: 150000,
    duration: 40,
    image: 'https://via.placeholder.com/300x200?text=Foot+Massage',
    rating: 4.7,
    reviewCount: 189,
    isActive: true,
  },
  {
    name: 'Spa Thư Giãn',
    nameEn: 'Relaxation Spa',
    description: 'Gói spa toàn bộ bao gồm massage và chăm sóc da',
    descriptionEn: 'Complete spa package with massage and skincare',
    category: 'spa',
    icon: '🛀',
    basePrice: 450000,
    duration: 90,
    image: 'https://via.placeholder.com/300x200?text=Spa',
    rating: 4.9,
    reviewCount: 312,
    isActive: true,
  },
  {
    name: 'Yoga & Stretching',
    nameEn: 'Yoga & Stretching',
    description: 'Hướng dẫn yoga và tập trãi giãn cơ thể',
    descriptionEn: 'Yoga guidance and body stretching',
    category: 'yoga',
    icon: '🧘',
    basePrice: 200000,
    duration: 60,
    image: 'https://via.placeholder.com/300x200?text=Yoga',
    rating: 4.6,
    reviewCount: 156,
    isActive: true,
  },
  {
    name: 'Skincare Chuyên Sâu',
    nameEn: 'Advanced Skincare',
    description: 'Chăm sóc da mặt chuyên sâu với các sản phẩm cao cấp',
    descriptionEn: 'Advanced facial skincare with premium products',
    category: 'skincare',
    icon: '✨',
    basePrice: 350000,
    duration: 75,
    image: 'https://via.placeholder.com/300x200?text=Skincare',
    rating: 4.8,
    reviewCount: 198,
    isActive: true,
  },
];

export const SAMPLE_THERAPISTS = [
  {
    name: 'Nguyễn Thị Hương',
    phoneNumber: '+84912345678',
    email: 'huong@massage.vn',
    gender: 'female',
    avatar: 'https://i.pravatar.cc/150?img=1&u=huong',
    bio: 'Chuyên gia massage 5 năm kinh nghiệm',
    bioEn: '5 years massage specialist',
    specialties: ['massage', 'spa'],
    experience: 5,
    rating: 4.9,
    reviewCount: 340,
    hourlyRate: 300000,
    distanceFromCenter: 2.5,
    isAvailable: true,
    languages: ['vi', 'en'],
    certifications: ['Professional Massage', 'Thai Massage'],
  },
  {
    name: 'Trần Văn Minh',
    phoneNumber: '+84923456789',
    email: 'minh@massage.vn',
    gender: 'male',
    avatar: 'https://i.pravatar.cc/150?img=2&u=minh',
    bio: 'Yoga instructor và chiropractor',
    bioEn: 'Yoga instructor and chiropractor',
    specialties: ['yoga', 'massage'],
    experience: 8,
    rating: 4.8,
    reviewCount: 289,
    hourlyRate: 350000,
    distanceFromCenter: 1.2,
    isAvailable: true,
    languages: ['vi', 'en', 'ch'],
    certifications: ['Certified Yoga', 'Chiropractor'],
  },
  {
    name: 'Phạm Thu Trang',
    phoneNumber: '+84934567890',
    email: 'trang@massage.vn',
    gender: 'female',
    avatar: 'https://i.pravatar.cc/150?img=3&u=trang',
    bio: 'Chuyên gia skincare và spa',
    bioEn: 'Skincare and spa specialist',
    specialties: ['spa', 'skincare', 'haircare'],
    experience: 6,
    rating: 4.7,
    reviewCount: 267,
    hourlyRate: 280000,
    distanceFromCenter: 3.1,
    isAvailable: true,
    languages: ['vi', 'en'],
    certifications: ['Professional Skincare', 'Spa Therapist'],
  },
  {
    name: 'Võ Thị Linh',
    phoneNumber: '+84945678901',
    email: 'linh@massage.vn',
    gender: 'female',
    avatar: 'https://i.pravatar.cc/150?img=4&u=linh',
    bio: 'Chân dung massage đặc biệt',
    bioEn: 'Specialized massage therapist',
    specialties: ['massage'],
    experience: 4,
    rating: 4.6,
    reviewCount: 198,
    hourlyRate: 250000,
    distanceFromCenter: 4.2,
    isAvailable: true,
    languages: ['vi'],
    certifications: ['Professional Massage'],
  },
];

// -------------------------------------------------------
// DỮ LIỆU GIẢ ĐỂ TEST — xóa khi có dữ liệu thật
// -------------------------------------------------------

export const MOCK_THERAPISTS: Therapist[] = [
  {
    id: 'mock-1',
    name: 'Hồng',
    phoneNumber: '+84901000001',
    email: 'hong@glow.vn',
    gender: 'female',
    avatar: '',
    photos: [
      'https://picsum.photos/seed/hong1/600/600',
      'https://picsum.photos/seed/hong2/600/600',
      'https://picsum.photos/seed/hong3/600/600',
      'https://picsum.photos/seed/hong4/600/600',
      'https://picsum.photos/seed/hong5/600/600',
      'https://picsum.photos/seed/hong6/600/600',
    ],
    bio: 'Chuyên viên massage dầu và giác hơi 5 năm kinh nghiệm',
    bioEn: '5 years oil & cupping massage specialist',
    specialties: ['Massage Dầu + Giác Hơi', 'Massage Dầu'],
    experience: 5,
    rating: 5.0,
    reviewCount: 69,
    hourlyRate: 280000,
    distanceFromCenter: 4,
    isAvailable: true,
    availability: {},
    languages: ['vi'],
    certifications: ['Chứng chỉ massage chuyên nghiệp'],
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'mock-2',
    name: 'Hương Giang Dưỡng',
    phoneNumber: '+84901000002',
    email: 'huonggiang@glow.vn',
    gender: 'female',
    avatar: '',
    photos: [
      'https://picsum.photos/seed/hgiang1/600/600',
      'https://picsum.photos/seed/hgiang2/600/600',
      'https://picsum.photos/seed/hgiang3/600/600',
      'https://picsum.photos/seed/hgiang4/600/600',
    ],
    bio: 'Kỹ thuật viên đá nóng và aroma',
    bioEn: 'Hot stone & aroma therapist',
    specialties: ['Massage Đá Nóng', 'Massage Aroma'],
    experience: 3,
    rating: 5.0,
    reviewCount: 20,
    hourlyRate: 260000,
    distanceFromCenter: 5,
    isAvailable: true,
    availability: {},
    languages: ['vi'],
    certifications: ['Chứng chỉ spa'],
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'mock-3',
    name: 'Thỏ',
    phoneNumber: '+84901000003',
    email: 'tho@glow.vn',
    gender: 'female',
    avatar: '',
    photos: [
      'https://picsum.photos/seed/tho1/600/600',
      'https://picsum.photos/seed/tho2/600/600',
      'https://picsum.photos/seed/tho3/600/600',
      'https://picsum.photos/seed/tho4/600/600',
      'https://picsum.photos/seed/tho5/600/600',
      'https://picsum.photos/seed/tho6/600/600',
    ],
    bio: 'Kỹ thuật viên mới, trẻ trung và nhiệt tình',
    bioEn: 'New, energetic therapist',
    specialties: ['Massage Thái', 'Massage Chân'],
    experience: 1,
    rating: 4.9,
    reviewCount: 77,
    hourlyRate: 230000,
    distanceFromCenter: 0.1,
    isAvailable: true,
    availability: {},
    languages: ['vi'],
    certifications: ['Chứng chỉ massage Thái'],
    createdAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'mock-4',
    name: 'Hoa',
    phoneNumber: '+84901000004',
    email: 'hoa@glow.vn',
    gender: 'female',
    avatar: '',
    photos: [
      'https://picsum.photos/seed/hoa1/600/600',
      'https://picsum.photos/seed/hoa2/600/600',
      'https://picsum.photos/seed/hoa3/600/600',
      'https://picsum.photos/seed/hoa4/600/600',
      'https://picsum.photos/seed/hoa5/600/600',
    ],
    bio: 'Chuyên gia massage cổ vai gáy và thư giãn toàn thân',
    bioEn: 'Neck, shoulder & full body relaxation expert',
    specialties: ['Massage Cổ Vai Gáy', 'Massage Không Dầu'],
    experience: 7,
    rating: 5.0,
    reviewCount: 102,
    hourlyRate: 300000,
    distanceFromCenter: 1,
    isAvailable: true,
    availability: {},
    languages: ['vi', 'en'],
    certifications: ['Chứng chỉ massage chuyên nghiệp', 'Massage trị liệu'],
    createdAt: '2023-05-01T00:00:00Z',
  },
  {
    id: 'mock-5',
    name: 'Lisa',
    phoneNumber: '+84901000005',
    email: 'lisa@glow.vn',
    gender: 'female',
    avatar: '',
    photos: [
      'https://picsum.photos/seed/lisa1/600/600',
      'https://picsum.photos/seed/lisa2/600/600',
      'https://picsum.photos/seed/lisa3/600/600',
      'https://picsum.photos/seed/lisa4/600/600',
    ],
    bio: 'Kỹ thuật viên massage chân và wax chuyên nghiệp',
    bioEn: 'Foot massage & wax specialist',
    specialties: ['Massage Chân', 'Wax Bikini'],
    experience: 4,
    rating: 4.9,
    reviewCount: 141,
    hourlyRate: 250000,
    distanceFromCenter: 2,
    isAvailable: true,
    availability: {},
    languages: ['vi'],
    certifications: ['Chứng chỉ chăm sóc cơ thể'],
    createdAt: '2023-09-01T00:00:00Z',
  },
  {
    id: 'mock-6',
    name: 'Mira Healing',
    phoneNumber: '+84901000006',
    email: 'mira@glow.vn',
    gender: 'female',
    avatar: '',
    photos: [
      'https://picsum.photos/seed/mira1/600/600',
      'https://picsum.photos/seed/mira2/600/600',
      'https://picsum.photos/seed/mira3/600/600',
    ],
    bio: 'Mới cập nhật – tắm tẩy tế bào chết Hàn Quốc và lấy ráy tai',
    bioEn: 'Korean full body scrub & ear cleaning',
    specialties: ['Tắm tẩy tế bào chết toàn thân Hàn Quốc', 'Lấy ráy tai'],
    experience: 2,
    rating: 4.8,
    reviewCount: 34,
    hourlyRate: 220000,
    distanceFromCenter: 3,
    isAvailable: true,
    availability: {},
    languages: ['vi'],
    certifications: ['Chứng chỉ chăm sóc da Hàn Quốc'],
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'mock-7',
    name: 'Minh Tuấn',
    phoneNumber: '+84901000007',
    email: 'minhtuan@glow.vn',
    gender: 'male',
    avatar: '',
    photos: [
      'https://picsum.photos/seed/mtuan1/600/600',
      'https://picsum.photos/seed/mtuan2/600/600',
      'https://picsum.photos/seed/mtuan3/600/600',
      'https://picsum.photos/seed/mtuan4/600/600',
      'https://picsum.photos/seed/mtuan5/600/600',
    ],
    bio: 'Kỹ thuật viên nam, massage Thái và thể thao',
    bioEn: 'Male therapist – Thai & sports massage',
    specialties: ['Massage Thái', 'Massage Dầu'],
    experience: 6,
    rating: 4.8,
    reviewCount: 88,
    hourlyRate: 290000,
    distanceFromCenter: 2.5,
    isAvailable: true,
    availability: {},
    languages: ['vi', 'en'],
    certifications: ['Chứng chỉ massage Thái', 'Sports Massage'],
    createdAt: '2023-03-01T00:00:00Z',
  },
  {
    id: 'mock-8',
    name: 'Thanh Thảo',
    phoneNumber: '+84901000008',
    email: 'thanhthao@glow.vn',
    gender: 'female',
    avatar: '',
    photos: [
      'https://picsum.photos/seed/tthao1/600/600',
      'https://picsum.photos/seed/tthao2/600/600',
      'https://picsum.photos/seed/tthao3/600/600',
      'https://picsum.photos/seed/tthao4/600/600',
    ],
    bio: 'Chuyên aroma và massage đá nóng thư giãn sâu',
    bioEn: 'Aroma & deep hot stone relaxation',
    specialties: ['Massage Aroma', 'Massage Đá Nóng'],
    experience: 5,
    rating: 4.7,
    reviewCount: 115,
    hourlyRate: 270000,
    distanceFromCenter: 1.5,
    isAvailable: false,
    availability: {},
    languages: ['vi'],
    certifications: ['Aromatherapy', 'Hot Stone Massage'],
    createdAt: '2023-07-01T00:00:00Z',
  },
];

export const SAMPLE_PROMOTIONS = [
  {
    code: 'WELCOME50',
    description: 'Giảm 50% cho đơn hàng đầu tiên',
    descriptionEn: '50% off first order',
    discountPercent: 50,
    maxDiscountAmount: 200000,
    minOrderAmount: 100000,
    expiryDate: '2027-12-31T23:59:59Z',
    maxUses: 1000,
    currentUses: 0,
    conditions: ['first_time_user'],
    isActive: true,
  },
  {
    code: 'SUMMER30',
    description: 'Giảm 30% toàn bộ dịch vụ spa',
    descriptionEn: '30% off all spa services',
    discountPercent: 30,
    maxDiscountAmount: 150000,
    minOrderAmount: 300000,
    expiryDate: '2027-09-30T23:59:59Z',
    maxUses: 500,
    currentUses: 0,
    conditions: ['spa_services_only'],
    isActive: true,
  },
  {
    code: 'REFERRAL20',
    description: 'Giảm 20% khi bạn bè giới thiệu',
    descriptionEn: '20% off with referral',
    discountPercent: 20,
    maxDiscountAmount: 100000,
    minOrderAmount: 0,
    expiryDate: '2027-12-31T23:59:59Z',
    maxUses: 10000,
    currentUses: 0,
    conditions: ['referral'],
    isActive: true,
  },
];
